config/routes.rb
PeercoinFaucet::Application.routes.draw do

  root 'main#index'
  post '/' => 'main#index'
  get '/requests' => 'main#requests', as: :requests

end

app/models/coin_request.rb
class CoinRequest < ActiveRecord::Base
  before_validation :strip_address
  validate :validate_address
  validates_presence_of :uniqueness_token
  validates_uniqueness_of :uniqueness_token
  validate :pending_address_uniqueness

  scope :fulfilled, -> { where(fulfilled: true) }
  scope :not_fulfilled, -> { where(fulfilled: false) }
  scope :first_in_first, -> { order(:created_at) }

  def strip_address
    self.address = self.address.strip if self.address
  end

  def validate_address
    unless Peercoin.address_valid?(address)
      errors.add(:address, :invalid)
    end
  end

  def pending_address_uniqueness
    if address.present?
      others = CoinRequest.not_fulfilled.where(address: address)
      others = others.where("id != ?", id) if id
      if others.any?
        errors.add(:address, "already has another pending request")
      end
    end
  end

  def self.fulfill!
    logger.info "Started fulfill"

    requests = not_fulfilled.first_in_first

    balance = Peercoin.balance
    logger.info "Balance: #{balance}"

    amount_per_request = FaucetConfig["amount_per_request"]
    raise "No amount per request provided in config" unless amount_per_request
    logger.info "Amount per request: #{amount_per_request}"

    number_to_fulfill = (balance / amount_per_request).floor
    logger.info "Number to fulfill: #{number_to_fulfill}"

    requests = requests.limit(number_to_fulfill).to_a.select(&:valid?)
    number_to_fulfill = requests.size
    logger.info "Number to fulfill after validation: #{number_to_fulfill}"

    loop do
      if number_to_fulfill < 1
        logger.info "No request remaining. Aborting"
        break
      end

      requests = requests[0, number_to_fulfill]
      logger.info "Requests selected: #{requests.inspect}"

      recipients = requests.map { |request| [request.address, amount_per_request] }.to_h
      logger.info "Sending #{recipients.inspect}"

      begin
        Peercoin.send_many(recipients)
        logger.info "Marking as fulfilled"
        requests.each do |request|
          request.update_attribute(:fulfilled, true)
        end

        logger.info "Fulfill done"
        break

      rescue Peercoin::InsufficientFunds
        logger.info "Not enought funds. Removing a request"
        number_to_fulfill -= 1
      end
    end
  end
end

app/models/state.rb
class State < ActiveRecord::Base
  serialize :last_transactions
  serialize :info

  def self.instance
    first_or_initialize
  end

  def self.update!
    state = instance
    state.address = Peercoin.address
    state.balance = Peercoin.balance
    state.last_transactions = Peercoin.transactions
    state.info = Peercoin.info
    state.save!
  end

  def testnet?
    info["testnet"]
  end

  def empty?
    balance <= FaucetConfig["amount_per_request"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  BLOCKED_DNSBL = YAML.load(Rails.root.join("config/blocked_dnsbl.yaml").read)

  before_filter :get_state

  def index
    @coin_request = CoinRequest.new
    @coin_request.attributes = params[:coin_request].permit(:address) if params[:coin_request]
    if request.post? or request.put?
      if FaucetConfig["captcha"]
        unless verify_recaptcha(model: @coin_request)
          flash.delete(:recaptcha_error)
          return
        end
      end

      ip = request.remote_ip

      dnsbl= DNSBL::Client.new
      matches = dnsbl.lookup(ip)
      matches.select! do |match|
        blocked_results = BLOCKED_DNSBL[match.dnsbl]
        blocked_results and blocked_results.has_key?(match.result)
      end
      if matches.any?
        message = "Your IP is blacklisted for the following reason(s): " + matches.map { |match| "#{match.meaning} (#{match.dnsbl})" }.join(", ")
        redirect_to root_path, flash: {error: message}
        return
      end

      # Ensure the client can actually receive data at this IP
      # (session cookie is signed, so it cannot be forged)
      raise "Invalid IP" unless session[:ip] == ip

      frame_duration = FaucetConfig.request_time_frame_duration
      time_frame = (Time.now.to_i / frame_duration).floor * frame_duration

      uniqueness_data = [time_frame, ip].to_yaml
      @coin_request.uniqueness_token = Digest::SHA1.hexdigest(uniqueness_data)

      if @coin_request.save
        redirect_to root_path, flash: {success: 'You request was created. It will be processed in the next batch or when enough funds are available'}
      end
    end
    session[:ip] = request.remote_ip
  end

  protected
  def get_state
    @state = State.instance
    @currency = FaucetConfig["currency"] || (@state.testnet? ? "testnet peercoin" : "peercoin")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.haml
!!!
%html{:lang => I18n.locale}
  %head
    %meta{charset: "utf-8"}/
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}/
    %title= content_for?(:title) ? yield(:title) : "Peercoin Faucet"
    = stylesheet_link_tag    "application", "data-turbolinks-track" => true
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    - if flash.any?
      %section#flashes
        - flash.each do |kind, message|
          .flash-container
            .flash{class: kind}
              = message
              %a.close{:href => "#"} &times;
    = yield
    = javascript_include_tag "application", "data-turbolinks-track" => true
    - if (code = FaucetConfig["tracking_code"]).present?
      != code

app/views/main/index.html.haml
- currency = @currency
- title = "#{currency} faucet".titleize
- content_for(:title, title)

%header.main-header
  .header-content
    %h1.title= title
    %p.intro
      On this site you can give or receive free #{currency.pluralize}
    - if @state.testnet?
      .testnet-warning
        .content #{currency.pluralize.capitalize} are not real coins. They are only useful for developpers and have absolutely no monetary value!
%section.main-content
  %article.receive-section
    .content
      %h2.title Receive #{currency.pluralize}
      %p.description
        You can receive #{pluralize FaucetConfig["amount_per_request"], currency} just by filling the form below.

      - if @state.empty?
        .empty-faucet-warning
          %p
            %strong Warning:
            The faucet is empty. Your request will not be processed until new coins are donated.
          - if (url = FaucetConfig["donation_request_url"]).present?
            %p You can request donations #{link_to "here", url}.
      .receive-form
        = form_for @coin_request, url: url_for do |f|
          - if @coin_request.errors.any?
            .errors
              .intro Some errors blocked your request:
              .list
                - @coin_request.errors.full_messages.each do |error|
                  .error= error
          .address-field
            = f.label :address, "Your #{currency} address"
            = f.text_field :address
          - if FaucetConfig["captcha"]
            .captcha
              = recaptcha_tags ssl: request.ssl?, ajax: true
          .submit
            = f.submit "Receive #{currency.pluralize}"
      %p.limit-notice
        Your IP is limited to 1 request every #{FaucetConfig["request_time_frame_duration"]}.
        %br
        Requests are fulfilled every #{FaucetConfig["time_between_request_fulfilling"]} if there is enough #{currency} given by donators.
  %article.give-section
    .content
      %h2.title Give #{currency.pluralize}
      %p.address Address: #{@state.address}
      %p.description
        Your can give to others by sending #{currency.pluralize} to the address above.
%section.bottom-section
  %article.state-section
    %h2.title Current state
    %p.current-balance Balance: #{pluralize @state.balance, currency}
    %p.last-transactions-intro Last transactions:
    %table.transaction-list
      %thead
        %tr
          %th.date Date (UTC)
          %th.category Category
          %th.amount Amount
          %th.address Address
          %th.confirmations Confirmations
          %th.fee Fee
      %tbody
        - (@state.last_transactions || []).reverse.each do |transaction|
          %tr.transaction-row
            %td.date= l(Time.zone.at(transaction["time"]), format: :short)
            %td.category= transaction["category"].humanize
            %td.amount= transaction["amount"]
            %td.address= transaction["address"]
            %td.confirmations= transaction["confirmations"]
            %td.fee= transaction["fee"]
    - pending_requests = CoinRequest.not_fulfilled
    %p.pending-requests-intro Pending requests (#{pending_requests.size}):
    %table.pending-requests
      %thead
        %tr
          %th.date Date (UTC)
          %th.address Address
      %tbody
        - pending_requests.each do |request|
          %tr.request-row
            %td.date= l(request.created_at, format: :short)
            %td.address= request.address
    .all-requests-link= link_to "All requests", requests_path
%footer#footer
  .content
    .links
      = link_to "Project page", "https://github.com/sigmike/peercoin-faucet"

  %a.github-ribbon{:href => "https://github.com/sigmike/peercoin-faucet"}
    = image_tag "forkme_right_gray_6d6d6d.png", alt: "Fork me on GitHub", style: "position: absolute; top: 0; right: 0; border: 0;"

app/views/main/requests.html.haml
- title = "Request list - " + "#{@currency} faucet".titleize
- content_for(:title, title)

%header.main-header
  .header-content
    %h1.title= title
%section.main-content
  - @requests = CoinRequest.order('created_at DESC').paginate(page: params[:page], per_page: params[:per_page] || 200)
  %table.request-table
    %thead
      %tr
        %th.date Date
        %th.address Address
        %th.sent Sent
    %tbody
      - @requests.each do |request|
        %tr
          %td.date= l(request.created_at)
          %td.address
            - if (url = FaucetConfig["explorer_url"]).present?
              - url = url.sub("{{ADDRESS}}", request.address)
              = link_to request.address, url
            - else
              = request.address
          %td.sent
            = request.fulfilled? ? "Yes" : "No"
  = will_paginate(@requests)